>>## word Embedding

### steps of one Word embedding
<ul>
    <li>define the vocabulary size.</li>
    <li>apply the one_hot on the sentence</li>
    <li>keep the equal length of one_hot by pad_sequences</li>
    <li>build the sequence model with embadding layer</li>
    <li>embadding layer tekes voca_size, dim_size , input_len</li>
    <li>compile the model optimizer 'adam',loss ='mse'</li>
    <li>predict the metrix based on the one_hot sentence representence</li>
</ul>

In [1]:
from tensorflow import keras

In [11]:
import numpy as np
from keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences      # to manage the no. of size equal
from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img,img_to_array,load_img
from keras.models import Sequential
from keras.layers import Embedding

In [3]:
sentence = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of words',
    'your video are good'
]

In [4]:
sentence

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your video are good']

In [6]:
vocabulary_size = 1000
# first you should have to define the vacabulary size
# vocabulary size should always be less then 10k

In [7]:
one_hot_rp = [one_hot(word,vocabulary_size) for word in sentence]
one_hot_rp
# it will return index value of my each word in vacabulary
# as you can see of the index is same because it is near to close.
# these are all index list for each sentence, and each elements of list 
# is defining the index no. of word in vocabulary

[[700, 644, 93, 324],
 [700, 644, 93, 154],
 [700, 719, 93, 569],
 [78, 825, 574, 901, 392],
 [78, 825, 574, 901, 314],
 [348, 700, 308, 93, 274],
 [292, 217, 990, 901]]

In [8]:
one_hot_rp[1][0]
# this index no. for "the" first word of senetence of the

700

In [12]:
# and now pass the onehot value from the embadding layer to get the form in metrix

In [13]:
no_of_word = 8
embedde_doc = pad_sequences(one_hot_rp,padding='pre',maxlen=no_of_word)
embedde_doc

# and now all the sentence length is equal
# padding pre means assign the 0 in starting in the sentence

array([[  0,   0,   0,   0, 700, 644,  93, 324],
       [  0,   0,   0,   0, 700, 644,  93, 154],
       [  0,   0,   0,   0, 700, 719,  93, 569],
       [  0,   0,   0,  78, 825, 574, 901, 392],
       [  0,   0,   0,  78, 825, 574, 901, 314],
       [  0,   0,   0, 348, 700, 308,  93, 274],
       [  0,   0,   0,   0, 292, 217, 990, 901]])

In [14]:
dimension_size = 10
model = Sequential()
model.add(Embedding(vocabulary_size,dimension_size,input_length=no_of_word))
model.compile('adam','mse')

In [15]:
model.layers

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             10000     
                                                                 
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
dimension_size = 10
model2 = Sequential()
model2.add(Embedding(input_dim = vocabulary_size,output_dim = dimension_size,input_length=no_of_word))
model2.compile('adam','mse')

# input_dim => means, total size of your vacabulary
# output_dim => means, it is like dimension how many feature you want to represent your world
# input_length => menas, how many maximum words exists in your sentence

In [19]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             10000     
                                                                 
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [22]:
embedd_sentence = model.predict(embedde_doc)
embedd_sentence

1/1 [==============================] - 0s 28ms/step


array([[[-0.04698304,  0.04461911, -0.01441292,  0.00850632,
         -0.00361644, -0.04404284,  0.0386782 , -0.04964647,
          0.04217695,  0.04537321],
        [-0.04698304,  0.04461911, -0.01441292,  0.00850632,
         -0.00361644, -0.04404284,  0.0386782 , -0.04964647,
          0.04217695,  0.04537321],
        [-0.04698304,  0.04461911, -0.01441292,  0.00850632,
         -0.00361644, -0.04404284,  0.0386782 , -0.04964647,
          0.04217695,  0.04537321],
        [-0.04698304,  0.04461911, -0.01441292,  0.00850632,
         -0.00361644, -0.04404284,  0.0386782 , -0.04964647,
          0.04217695,  0.04537321],
        [ 0.03955872,  0.04794041,  0.00169332, -0.01036645,
         -0.01169121, -0.01298402,  0.02124994, -0.01664462,
         -0.04683408, -0.03414017],
        [ 0.03196928,  0.04050609, -0.03667284, -0.00611796,
         -0.00571924, -0.00783659, -0.00399697, -0.04782629,
         -0.02764943,  0.0304986 ],
        [ 0.02038963,  0.01352341, -0.02040694,  0.0

In [23]:
embedd_sentence.shape

# 7  => difining the length of sentence
# 8  => difining the no. of word in sentence
# 10 => difining the feature in which single word has been converted

(7, 8, 10)

In [26]:
sentence[1]

'the glass of juice'

In [27]:
one_hot_rp[1]

[700, 644, 93, 154]

In [25]:
embedde_doc[1]

array([  0,   0,   0,   0, 700, 644,  93, 154])

In [28]:
embedd_sentence[1]

array([[-0.04698304,  0.04461911, -0.01441292,  0.00850632, -0.00361644,
        -0.04404284,  0.0386782 , -0.04964647,  0.04217695,  0.04537321],
       [-0.04698304,  0.04461911, -0.01441292,  0.00850632, -0.00361644,
        -0.04404284,  0.0386782 , -0.04964647,  0.04217695,  0.04537321],
       [-0.04698304,  0.04461911, -0.01441292,  0.00850632, -0.00361644,
        -0.04404284,  0.0386782 , -0.04964647,  0.04217695,  0.04537321],
       [-0.04698304,  0.04461911, -0.01441292,  0.00850632, -0.00361644,
        -0.04404284,  0.0386782 , -0.04964647,  0.04217695,  0.04537321],
       [ 0.03955872,  0.04794041,  0.00169332, -0.01036645, -0.01169121,
        -0.01298402,  0.02124994, -0.01664462, -0.04683408, -0.03414017],
       [ 0.03196928,  0.04050609, -0.03667284, -0.00611796, -0.00571924,
        -0.00783659, -0.00399697, -0.04782629, -0.02764943,  0.0304986 ],
       [ 0.02038963,  0.01352341, -0.02040694,  0.03575165, -0.00265766,
         0.01012754, -0.04764963, -0.02330877

In [29]:
embedd_sentence[1].shape

(8, 10)

In [35]:
first_sentence_embed = pd.DataFrame(embedd_sentence[1],index=embedde_doc[1]).T
print(sentence[1])
first_sentence_embed

the glass of juice


0         0         0         0         700       644       93   \
0 -0.046983 -0.046983 -0.046983 -0.046983  0.039559  0.031969  0.020390   
1  0.044619  0.044619  0.044619  0.044619  0.047940  0.040506  0.013523   
2 -0.014413 -0.014413 -0.014413 -0.014413  0.001693 -0.036673 -0.020407   
3  0.008506  0.008506  0.008506  0.008506 -0.010366 -0.006118  0.035752   
4 -0.003616 -0.003616 -0.003616 -0.003616 -0.011691 -0.005719 -0.002658   
5 -0.044043 -0.044043 -0.044043 -0.044043 -0.012984 -0.007837  0.010128   
6  0.038678  0.038678  0.038678  0.038678  0.021250 -0.003997 -0.047650   
7 -0.049646 -0.049646 -0.049646 -0.049646 -0.016645 -0.047826 -0.023309   
8  0.042177  0.042177  0.042177  0.042177 -0.046834 -0.027649 -0.032767   
9  0.045373  0.045373  0.045373  0.045373 -0.034140  0.030499  0.008103   

        154  
0  0.045405  
1  0.026129  
2  0.030704  
3  0.023186  
4 -0.041926  
5 -0.044389  
6 -0.028577  
7 -0.043855  
8 -0.006736  
9 -0.029998

In [36]:
first_sentence_embed.columns = [0,0,0,0,'The','glass','of','juice']
first_sentence_embed

0         0         0         0       The     glass        of  \
0 -0.046983 -0.046983 -0.046983 -0.046983  0.039559  0.031969  0.020390   
1  0.044619  0.044619  0.044619  0.044619  0.047940  0.040506  0.013523   
2 -0.014413 -0.014413 -0.014413 -0.014413  0.001693 -0.036673 -0.020407   
3  0.008506  0.008506  0.008506  0.008506 -0.010366 -0.006118  0.035752   
4 -0.003616 -0.003616 -0.003616 -0.003616 -0.011691 -0.005719 -0.002658   
5 -0.044043 -0.044043 -0.044043 -0.044043 -0.012984 -0.007837  0.010128   
6  0.038678  0.038678  0.038678  0.038678  0.021250 -0.003997 -0.047650   
7 -0.049646 -0.049646 -0.049646 -0.049646 -0.016645 -0.047826 -0.023309   
8  0.042177  0.042177  0.042177  0.042177 -0.046834 -0.027649 -0.032767   
9  0.045373  0.045373  0.045373  0.045373 -0.034140  0.030499  0.008103   

      juice  
0  0.045405  
1  0.026129  
2  0.030704  
3  0.023186  
4 -0.041926  
5 -0.044389  
6 -0.028577  
7 -0.043855  
8 -0.006736  
9 -0.029998

In [38]:
# word embedded 😁